catalog/urls.py
from catalog.views import index

from django.urls import path


app_name = 'catalog'
urlpatterns = [
    path('', index, name='index'),
]

hwsite/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('', include('triangle.urls')),
    path('catalog/', include('catalog.urls')),
    path('admin/', admin.site.urls),
]

triangle/urls.py
from django.urls import path

from triangle.views import index, person_form, person_list, person_update_form, trngl_form


app_name = 'triangle'
urlpatterns = [
    path('', index, name='index'),
    path('person/', person_form, name='person-form'),
    path('personlist/', person_list, name='person-list'),
    path('person/<int:pk>/', person_update_form, name='person-update-form'),
    path('triangle/', trngl_form, name='triangle-form'),
]

catalog/models.py
from django.db import models


class PropertyName(models.Model):
    property_name = models.CharField(max_length=200)

    def __str__(self):
        return self.property_name


class Properties(models.Model):
    name = models.ForeignKey('PropertyName', on_delete=models.CASCADE)
    property_value = models.CharField(max_length=200)

    def __str__(self):
        return f'{self.name}: {self.property_value}'


class PropertySet(models.Model):
    exchange_id = models.CharField(max_length=200)
    property_set_name = models.CharField(max_length=200)
    properties = models.ManyToManyField('Properties')

    def __str__(self):
        j = str()
        k = self.properties.all()
        for i, item in enumerate(k):
            j += str(item)
            if i != len(k) - 1:
                j += '; '
        return f'{j}'


class FeatureName(models.Model):
    exchange_id = models.CharField(max_length=200)
    feature_name = models.CharField(max_length=200)

    def __str__(self):
        return self.feature_name


class Features(models.Model):
    name = models.ForeignKey('FeatureName', on_delete=models.CASCADE)
    feature_value = models.CharField(max_length=200, unique=False)

    def __str__(self):
        return f'{self.name}: {self.feature_value}'


class Inventories(models.Model):
    exchange_id = models.CharField(max_length=200)
    inventory_name = models.CharField(max_length=200)
    group = models.ForeignKey('Group', on_delete=models.CASCADE)
    features = models.ManyToManyField('Features')
    property_set = models.ManyToManyField('PropertySet')
    vendor_codes = models.OneToOneField('VendorCodes', on_delete=models.CASCADE)

    def __str__(self):
        return self.inventory_name


class VendorCodes(models.Model):
    vendor_code_company = models.CharField(max_length=20)
    vendor_code_supplier = models.CharField(max_length=20)

    def __str__(self):
        return self.vendor_code_company


class GroupPath(models.Model):
    ancestor = models.ForeignKey(
        'Group',
        null=True,
        db_column='ancestor',
        blank=True,
        related_name="ancestor",
        on_delete=models.CASCADE
    )
    descendant = models.ForeignKey(
        'Group',
        null=True,
        db_column='descendant',
        blank=True,
        related_name="descendants",
        on_delete=models.CASCADE
    )
    path_length = models.IntegerField(null=True, db_column='PathLength', blank=True)

    class Meta:
        db_table = u'GroupPath'

    def __str__(self):
        return f'ancestor: {self.ancestor}, descendant: {self.descendant}, path_length: {self.path_length}'


class Group(models.Model):
    exchange_id = models.CharField(max_length=200)
    group_name = models.CharField(max_length=200)
    parent = models.ForeignKey(
        'self',
        null=True,
        blank=True,
        default=None,
        related_name='children',
        on_delete=models.CASCADE
    )
    group_path = models.ManyToManyField('Group', through='GroupPath', through_fields=('ancestor', 'descendant'))

    class Meta:
        db_table = u'Group'

    def __str__(self):
        return self.group_name

triangle/models.py
from django.db import models


class Person(models.Model):
    first_name = models.CharField(max_length=200, verbose_name="First name")
    last_name = models.CharField(max_length=200, verbose_name="Last name")
    email = models.EmailField()

    def __str__(self):
        return self.last_name


class Logs(models.Model):
    path = models.CharField(max_length=300, verbose_name='Path')
    request_method = models.CharField(max_length=50, verbose_name='Request method')
    form_data = models.JSONField(verbose_name='Form data')
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.path

triangle/forms.py
from django import forms

from triangle.models import Person


class TriangleForm(forms.Form):
    leg_one = forms.IntegerField(label='leg 1', min_value=1, required=True)
    leg_two = forms.IntegerField(label='leg 2', min_value=1, required=True)


class PersonForm(forms.ModelForm):
    class Meta:
        model = Person
        fields = ['first_name', 'last_name', 'email']

catalog/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'catalog/index.html', {})

triangle/views.py
from django.shortcuts import get_object_or_404, redirect, render

from triangle.forms import PersonForm, TriangleForm
from triangle.models import Person


def index(request):
    return render(request, 'triangle/index.html', {})


def trngl_form(request):
    hypo = None
    if 'calculate' in request.GET:
        form = TriangleForm(request.GET)
        if form.is_valid():
            leg_one = form.cleaned_data["leg_one"]
            leg_two = form.cleaned_data["leg_two"]
            hypo = (leg_one ** 2 + leg_two ** 2) ** 0.5
    else:
        form = TriangleForm()
    return render(
        request,
        'triangle/triangle_form.html',
        {
            'get_trngl_form': form,
            'hypothesis': hypo,
        }
    )


def person_form(request):
    if request.method == 'POST':
        pers_form = PersonForm(request.POST)
        if pers_form.is_valid():
            pers_form.save()
            return redirect('triangle:person-list')
    else:
        pers_form = PersonForm()
    return render(
        request,
        'triangle/person.html',
        {
            'formset': pers_form
        }
    )


def person_update_form(request, pk):
    person = get_object_or_404(Person, pk=pk)
    if request.method == 'POST':
        pers_form = PersonForm(request.POST, instance=person)
        if pers_form.is_valid():
            pers_form.save()
            return redirect('triangle:person-list')
    else:
        pers_form = PersonForm(instance=person)
    return render(
        request,
        "triangle/person_update.html",
        {
            'formset': pers_form,
            'person': person
        }
    )


def person_list(request):
    person_queryset = Person.objects.all()
    return render(request, 'triangle/person_list.html', {'persons': person_queryset})

templates/catalog/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Catalog</title>
</head>
<body>
  <p>Hello, Catalog</p>
  <p><a href="{% url 'triangle:index' %}">Home</a></p>

</body>
</html>

templates/triangle/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Triangles</title>
</head>
<body>
    <h1>Hello, Hillel Homeworks</h1>
    <h2>HW_8: Triangle</h2>
        <p><a href="{% url 'triangle:triangle-form' %}">Triangle</a></p>
    <h2>HW_9: Catalog</h2>
        <p><a href="{% url 'catalog:index' %}">Catalog</a></p>
    <h2>HW_10: Person</h2>
        <p><a href="{% url 'triangle:person-form' %}">Person</a></p>
        <p><a href="{% url 'triangle:person-list' %}">Person list</a></p>
</body>
</html>

templates/triangle/person.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Person</title>
</head>
<body>
  <h1>Create New Person</h1>
  <p><a href="{% url 'triangle:index' %}">Home</a></p>
  <p><a href="{% url 'triangle:person-list' %}">Person list</a></p>
    <form action="{% url 'triangle:person-form' %}" method="post">
        {% csrf_token %}
        {{ formset.as_p }}
        <input type="submit" name="Save" value="Save">
    </form>
</body>
</html>

templates/triangle/person_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Person list</title>
</head>
<body>
    <h1>Person list</h1>
    <a href="{% url 'triangle:index' %}">Home</a>
    <ul>
    {% for person in persons %}
        <li><a href="{% url 'triangle:person-update-form' pk=person.pk %}" >{{ person.first_name }} {{ person.last_name }}</a></li>
    {% endfor %}
    </ul>

    <a href="{% url 'triangle:person-form' %}">Create new person?</a>
</body>
</html>

templates/triangle/person_update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Person</title>
</head>
<body>
  <h1>Update Person: {{ person.first_name }} {{ person.last_name }}</h1>
  <p><a href="{% url 'triangle:index' %}">Home</a></p>
  <p><a href="{% url 'triangle:person-list' %}">Person list</a></p>

    <form action="{% url 'triangle:person-update-form' pk=person.pk %}" method="post">
        {% csrf_token %}
        {{ formset.as_p }}
        <input type="submit" name="Save" value="Save">
    </form>
</body>
</html>

templates/triangle/triangle_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Triangle form</title>
</head>
<body>
    <h1>Triangle form</h1>
    <p><a href="{% url 'triangle:index' %}">Home</a></p>
    {% if hypothesis %}
    <h2>Hypothesis = {{ hypothesis }}</h2>
    {% endif %}
    <form action="{% url 'triangle:triangle-form' %}" method="get">
        {% csrf_token %}
        {{ get_trngl_form.as_p }}
        <input type="submit" name="calculate" value="Calculate">
    </form>
</body>
</html>